##### Standard Prompt #####

:stdprompt:
  # current working directory
  :start: '\[\033[0;32m\]\w\[\033[0m\] '

  # Military time
  :end: '\n\A \$ '


##### Git Prompt #####

:git:
  :status:
    :color: green
    :symbol: ✔

  :staged:
    :symbol: ●
    :color: red

  :untracked:
    :symbol: …

  :modified:
    :symbol: ✚
    :color: blue

  :unmerged:
    :symbol: ✖
    :color: yellow

  :ahead:
    :symbol: ↑

  :behind:
    :symbol: ↓

  :sha:
    :symbol: '#'
    :color: yellow

  :branch:
    :color: magenta

  :layout: (branchbehindahead|stagedmodifieduntrackedunmergedstatus) sha

:rvm:
  :ruby:
    :color: red
    :symbol: ∆

  :gemset:
    :color: yellow
    :symbol: ›

  :layout: ruby gemset